---
title: "Data Cleaning and Exploratory Analysis"
author: "James "Mac" Stewart"
date: '2023-04-24'
output: html_document
---

# Data Cleaning and Exploratory Analysis

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R

## Necessary Packages

```{R}
library(tidyverse)
library(tidymodels)
library(GGally)
library(reticulate)
library(leaps)
library(forcats)
library(caret)
```

## Importing Data

The following code chunk was taken from [tidy Tuesday](https://github.com/rfordatascience/tidytuesday/blob/master/data/2023/2023-04-04/readme.md) where we pull in data. I chose to use their data cleaning code as this is not the main goal of the project.

The data that we are using here is regarding Premier League matches in the 2021-2022 season. While this gives us the full game data, I will only be using the data that doesn't specify who wins. For instance, I will not be using the full time goals. I am hoping to predict who wins the game using both simple and multiple logistic regression. For these, I will only use the games with a decisive winner. After, I will use a multinomial logistic model and use the 'D' level outcomes.

```{R}
soccer <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-04-04/soccer21-22.csv')
```

The primary variable that we will be trying to predict is called FTR or full time result. This is a character variable that states either H or A for home or away team. 

## R

### Data Cleaning

The first thing that I need to do is remove the full time goals. These are directly related to who wins so it would not be good to include. I will also be removing the date variable as I will not be doing any time series analysis.

```{R}
soccer2 <- soccer %>%
  select(-FTHG, -FTAG, -Date)
```

The next thing I want to do is simplify the referee, hometeam, and awayteam variables as I believe there will be too many levels to these factor variables;

```{R}
## looking at referee variable
soccer2 %>%
  count(Referee) %>%
  group_by(Referee)

## looking at hometeam
soccer2 %>%
  count(HomeTeam) %>%
  group_by(HomeTeam)

## looking at awayteam
soccer2 %>%
  count(AwayTeam) %>%
  group_by(AwayTeam)

```

There are 22 different Referees and 20 different teams. Because of how many teams/referees there are, I am going to leave these variables out. However, they might be looked at later if time allows.

```{R}
soccer2 <- soccer2 %>%
  select(-Referee, -HomeTeam, -AwayTeam)
```

For the first set of regressional analysis, I will only be using the games that had a decisive home or away team winner. The following code chunk creates a new dataset with only those. This drops out approximately 88 rows of data.

```{R}
soccer_decisive <- soccer2 %>%
  filter(FTR != 'D')
```

Next, I'm going to create factors out of the FTR and HTR so that they can be treated as such. I will do this for both the full soccer2 dataset and the soccer_decisive datasets.

```{R}
# full dataset
soccer2$FTR <- as.factor(soccer2$FTR)
soccer2$HTR <- as.factor(soccer2$HTR)

#decisive dataset
soccer_decisive$FTR <- as.factor(soccer_decisive$FTR)
soccer_decisive$HTR <- as.factor(soccer_decisive$HTR)

```

## Exploratory Data Analysis

Here, I am going to do some basic exploratory data analysis to see important information about each of the variables.

Knowledge on how to get this summary table was taken from [Statology](https://www.statology.org/summary-statistics-in-r-dplyr/)

```{R}
soccer_decisive %>%
  summarise(across(where(is.numeric), .fns = list(
    min = min,
    median = median,
    average = mean,
    stdev = sd,
    max = max
  ))) %>%
  pivot_longer(everything(), names_sep = '_', names_to=c('variable', '.value'))

```

There doesn't seem to be anything majorly off with these variables. Now I am going to use ggpairs() to see the relationship between each pair of variables.

```{R}
soccer_decisive %>%
  ggpairs()
```

While it is hard to see with these visualizations, there do appear to be some relationships. Specifically, you can see some interactions between HS-AS, HS-HST, HS-AST, AS-AST, and AS-AC. If these variables are significant predictors in the model, we might include their interaction affects.

# python

## Necessary Packages

```{python}
# packages
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
```

As stated, because I have already cleaned data in the linear regression section, this will be less in-depth. However, there are some additional things done in this section so I will go through it.

## Importing Data

```{python}
# reading in the data
soccer = pd.DataFrame(r.soccer)

# dropping unneeded variables
soccer2 = soccer.drop(["FTHG", "FTAG", "Date"])
```

Next, I need to create frequency tables for each of the categorical variables. This is not something that was done in the linear regression data cleaning. To do this, I will utilize the pandas .value_counts()

```{python}
soccer['Referee'].value_counts()
print("")
soccer['HomeTeam'].value_counts()
print("")
soccer['AwayTeam'].value_counts()
```

This process felt a lot easier utilizing the functions in pandas and didn't require a dplyr pipeline.

The next step was dropping these categorical values and making the other ones as factors. Again, these will be created as category type variables in python.

```{python}
# dropping variables
soccer2 = soccer.drop(['Referee','HomeTeam','AwayTeam'], axis = 1)

# creating category variables
soccer2[['FTR','HTR']] = soccer2[['FTR','HTR']].astype('category')
```

Next, a second data set was created that only included games that had a decisive win (either the home or away team won).

```{python}
soccer_decisive = soccer2[soccer2['FTR'] != 'D']
```

Filtering is pretty much the same for both.

The next thing that we did was create a summary statistics table.

```{python}
summary = soccer2.describe()
summary
```

This was relatively simple in python. Pandas provides a .describe() function that returns summary statistics for all of the columns included in the dataframe. I have it saved as a separate dataframe so that it can be viewed in it's entirety. You could transpose this table to have it flipped with each row being a variable but that doesn't seem necessary.

Finally, we create the ggpairs() table that was created.

```{python}
plt.tight_layout()
g = sns.PairGrid(soccer2)
g.map_diag(sns.histplot)
g.map_lower(sns.scatterplot, size = .1)
plt.show()
```

## Exporting Data

```{R}
write.csv(soccer2, "~/R/sta631/language-comparison/logistic-regression/Data/soccer.csv", row.names = FALSE)
write.csv(soccer_decisive, "~/R/sta631/language-comparison/logistic-regression/Data/soccer_binary.csv", row.names = FALSE)
```

# Overall Assessment

When it comes to this batch of data cleaning, it seemed that python and the use of pandas was better with doing these basic functions. However, there was still a drawback with the exploratory visualization creation in python in comparison to the ease of doing them in r.
